
# Dataset
train_dataset_aug_path: data/cifar10/train_aug
train_dataset_plain_path: data/cifar10/train_plain
test_dataset_path: data/cifar10/test

img_size: 32
num_classes: 10

global_crop_ratio: !!python/tuple [0.4, 1.0]
local_crop_ratio: !!python/tuple [0.05, 0.4]

nb_local_crops: 8

dataset_means: [0.4914, 0.4822, 0.4465]
dataset_stds: [0.2023, 0.1994, 0.2010]

# Training
batch_size: 512
epochs: 60

# Model
encoder_type: vit
out_dim: 200
hidden_dim: 512
bottleneck_dim: 64

teacher_momentum: 0.996

# Encoder
enc_out_dim: 192

#ViT
depth: 12
num_heads: 3
mlp_ratio: 4.

# Eval
batch_size_eval: 128

# Optimizer
optimizer: adamw
weight_decay: 0.